[MERGE] GE7: Motorcyle Registry Manufacturing Enhancements
vmac-odoo/team2-kawiil-motors pull request #8
Opened 2023-07-27 21:57 UTC by vmac-odoo

Features:
- This module integrates sales/mrp to motorcycle registry

2023-07-28 17:25 UTC, ayhp-odoo requested changes

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/__init__.py
> +from . import models
New line at the end of the file and all the other files where are missing

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/models/__init__.py
> +from . import stock_lot
Sort imports in aphabetical order

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/models/motorcycle_registry.py
> +from odoo import models, fields, api
The imports should be sorted in alphabetical order and check the Odoo guidelines the correct order to sort the import, first go the python libraries then goes the imports from odoo and finally the imports of odoo addons

https://www.odoo.com/documentation/16.0/contributing/development/coding_guidelines.html?highlight=guidelines#imports

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/models/motorcycle_registry.py
> +        for record in self:
Use a more descriptive word to name the current value of the loop as you did in the for above

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/models/stock_lot.py
> +
Two lines should be betwwen the imports and the declaration of the class

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/views/motorcycle_registry_views_inherit.xml
> +
Remove unnecessary blank spaces

2023-07-28 17:25 UTC, ayhp-odoo commented on ge07_team02/views/motorcycle_registry_views_inherit.xml
> +                <page attrs="{'invisible': ''}" string="Motorcycle Tracking Info">
why invisible is empty?

2023-07-31 16:42 UTC, vmac-odoo commented on ge07_team02/__init__.py
> +from . import models
Fixed

2023-07-31 16:42 UTC, vmac-odoo commented on ge07_team02/models/__init__.py
> +from . import stock_lot
Fixed

2023-07-31 16:43 UTC, vmac-odoo commented on ge07_team02/models/motorcycle_registry.py
> +        for record in self:
Fixed

2023-07-31 16:43 UTC, vmac-odoo commented on ge07_team02/views/motorcycle_registry_views_inherit.xml
> +
Fixed

2023-07-31 16:43 UTC, vmac-odoo commented on ge07_team02/views/motorcycle_registry_views_inherit.xml
> +                <page attrs="{'invisible': ''}" string="Motorcycle Tracking Info">
Fixed

2023-07-31 16:49 UTC, ayhp-odoo approved these changes

2023-07-31 18:03 UTC, merged